# Generated by Django 4.2.2 on 2023-06-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='projects',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
