# Generated by Django 4.2.2 on 2023-06-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0003_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
