# Generated by Django 4.2.2 on 2023-06-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0004_remove_person_first_name_remove_person_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='user',
            new_name='person',
        ),
    ]
