# Generated by Django 4.2.2 on 2023-07-10 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0008_person_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='pfapp.person'),
        ),
        migrations.AlterField(
            model_name='work',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='pfapp.person'),
        ),
    ]
