# Generated by Django 4.2.2 on 2023-07-13 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0009_alter_projects_person_alter_work_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_set', to='pfapp.person'),
        ),
        migrations.AlterField(
            model_name='work',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_set', to='pfapp.person'),
        ),
    ]
