# Generated by Django 4.2.2 on 2023-07-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0010_person_desc_person_github_person_hobbies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
